### ISSUE TITLE
Getting the thing to run - issue with start up task not starting

### ISSUE THREAD

**Issue by sprintstar** [TechDevils/Url-Task-Scheduler#6]
I'm sure I'm just missing a step.  Package is installed and a task added. However the next run time comes and goes and the task is not run.  What do I need to do to get the tasks to run? Umbraco v7.2.5

**Comment by Chadders13** [comment]
Can you check in the umbraco logs there should be some information about the Keep alive Task that will ensure that the app pool doesn't spin down. if you can find this text "Started keep alive task !!" it will be running and might be something else :)

as long as you have a vaild url in this app setting ('< add key="KeepAliveUrl" value="http://urlschduler.local/umbraco" />') for your website then it should call it every few mins to ensrue that it stays alive

**Comment by sprintstar** [comment]
I can't find "Started keep alive task !!" in any log files. Could you expand on your second paragraph a little?

**Comment by akeilox** [comment]
cant see it either. using 7.1.8, tried on 7.2 as well

**Comment by Chadders13** [comment]
sorry forgot the app setting in the comment :grimacing:

**Comment by Chadders13** [comment]
in the start up file it should be kicking that task to keep the app pool alive.

When the app installed it should have stuck that app setting in the web.config

that might be one reason its not keeping alive but can you check your logs for **"Pre app start task"**

**Comment by sprintstar** [comment]
So in my case I have a website monitor program that requests a page every 10 minutes, but is this not enough?  I am aware of the KeepAliveUrl app setting, but I thought your package did the same thing (only better)?

I have two instances of "Pre app start task" in my logs, both around the time of an application restart I triggered.

**Comment by Chadders13** [comment]
Ok sounds like the app is running.

Next thing to look for is **"Ran TechDevils Job :"** and **"Failed TechDevils Job"**

(it should be running better in theory :grimacing:)

**Comment by sprintstar** [comment]
There are no instances of either of those strings in any file (other than TechDevils.UrlTaskScheduler.dll).

Can I get clarification on how the package works please? So upon any request of any umbraco page (hence the need for an external 'keep alive' mechanism), your code runs, finds any jobs that need running, and runs them?  Is that it in a nutshell?

**Comment by Chadders13** [comment]
That's about it in brife. Any of the enabled tasks that need to be run based on there next run time will be run. 

That sounds like something is not firing the task I'll investigate and get back to you.

**Comment by Chadders13** [comment]
Found the bug ill upload a new version with the fix in it shortly.

**Comment by Chadders13** [comment]
Hi, 

iv update the version. if you replace your dll with the one in version 1.1.6 this should fix the issue you where both having. https://our.umbraco.org/projects/backoffice-extensions/url-task-scheduler-for-v7/

**Comment by sprintstar** [comment]
I can confirm this new version fixes the issue and my tasks are fired. Thank you for taking the time to fix it. Its a great package!

**Comment by Chadders13** [comment]
your welcome :smile: 

if you find anything else let me know and i'll take look :smile:

**Comment by akeilox** [comment]
I have just uploaded the latest version and it doesnt seem to work, perhaps there might be another issue.
The URL i am calling (the website itself) is https so i capture the address with http and check SSL checkbox, when i click run the last run time shows as 0001-01-01T00:00:00
The url is not being hit, if i copy and paste (adding https://) the url it opens up just fine, so there should be something in between that UTS not proceeding.
Is there any configuration needs to be done for https links? beside checking the box
